"""Initial migration

Revision ID: 02ae4bf3f067
Revises: 
Create Date: 2023-08-07 23:38:51.817320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ae4bf3f067'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ua_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Text(length=36), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.JSON(), nullable=True),
    sa.Column('name_lower', sa.String(), nullable=False),
    sa.Column('post_code', sa.JSON(), nullable=True),
    sa.Column('katottg', sa.String(), nullable=True),
    sa.Column('koatuu', sa.String(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('coordinates_added_manually', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('public_name', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('ua_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ua_settlements_name_lower'), ['name_lower'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ua_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ua_settlements_name_lower'))

    op.drop_table('ua_settlements')
    # ### end Alembic commands ###
